spring:
  datasource:
    url: jdbc:postgresql://${HS_HAPI_DB_HOST}:${HS_HAPI_DB_PORT}/${HS_HAPI_DB_NAME}
    username: ${HS_HAPI_DB_USER}
    password: ${HS_HAPI_DB_PASSWD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect

