POST http://localhost:18080/fhir/CodeSystem
Content-Type: application/json+fhir

< ./codesystem-example.json

###
POST http://localhost:18080/fhir/$reindex?everything=true
Content-Type: application/fhir+json

{
  "resourceType": "Parameters",
  "parameter": [ ]
}